### ISSUE TITLE
Auto Scroll

### ISSUE THREAD

**Issue by Zeneel** [gcla/termshark#10]
Would it possible to add a shortcut to enable auto scrolling of the packet capture rows in the main window as with wireshark?

Really liking this project!

**Comment by gcla** [comment]
Hi - this feature is now present in HEAD. Let me know what you think!

You can enable it permanently by adding to `~/.config/termshark/termshark.toml` - or the XDG equivalent on OSX or Windows - like this:

```toml
[main]
  auto-scroll = true
```

Or you can add `--auto-scroll` to the command-line.

**Comment by pm-pm** [comment]
Command line does not work (anymore)?
Using termshark 2.1.1

**Comment by pocc** [comment]
@pm-pm You should create a new issue because this one is almost a year old. If you do create a new issue, please provide more context (and perhaps screenshots) so we know what you're talking about :)

**Comment by gcla** [comment]
Hi @pm-pm - yes you're right, I silently removed the command-line option. I should've put that in the Changelog... My thinking was that auto-scroll was probably an option that a user would (almost) always have either on or off, according to their preference, rather than on a pcap-by-pcap basis. Could you let me know what you think - is that assumption wrong for you and likely others? It's still in the toml/config file. I've been considering adding a simple preferences screen to the tui that reflects some of the settings in the toml file. Would that work for your uses - just toggling it back and forth via preferences? Or would you really prefer it back on the command line?
