### ISSUE TITLE
Typographical Error in README

### ISSUE THREAD

**Issue by evandrix** [gcla/termshark#105]
https://github.com/gcla/termshark/blob/master/README.md#building
~~go get github.com/gcla/termshark/v2/cmd/termshark~~
`go get github.com/gcla/termshark/cmd/termshark`

**Comment by gcla** [comment]
Hi @evandrix - thanks for the report! This tripped me up at first but I think the correct command is the v2 version. Does it work for you? If I try
```
go get github.com/gcla/termshark/v2/cmd/termshark
```
then run `~/go/bin/termshark -v` I see
```
termshark v2.2.0
```
but if I run
```
go get github.com/gcla/termshark/cmd/termshark
```
and run it I see
```
termshark v<localbuild>
```
This happens because as of v2.0 of termshark, I changed the module name in `go.mod` to:
```
module github.com/gcla/termshark/v2
```

There's an explanation here: https://stackoverflow.com/a/53380636/784226
(I'm using go 1.15 and `GO111MODULE=on`)

**Comment by evandrix** [comment]
doing it my way:
1. `go version go1.15.6 darwin/amd64`
2. `GO111MODULE=on`
3. `termshark v2.2.0` (SHA1:46cff02246b3b14252b689cfc1b896d1cfddc70c)

trying it your way:
```
$ go get -u -v github.com/gcla/termshark/v2/cmd/termshark
github.com/gcla/termshark (download)
cannot find package "github.com/gcla/termshark/v2/cmd/termshark" in any of:
	/usr/local/Cellar/go/1.15.6/libexec/src/github.com/gcla/termshark/v2/cmd/termshark (from $GOROOT)
	$HOME/go/src/github.com/gcla/termshark/v2/cmd/termshark (from $GOPATH)
```

-shrug- idk, still couldn't get it to work your way, but i do have the same version reported by the binary, so i guess it's okay

**Comment by evandrix** [comment]
okay no crap, you're absolutely right.

I *thought* `GO111MODULE=on` was enabled in my shell, but it wasn't ... grrr

just ignore my issue pls, thanks for your help
