### ISSUE TITLE
termshark does not exit gracefully when killed

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#11]
1. In one terminal, enter `termshark -i <interface>` to start a capture
2. In another terminal, enter `killall termshark`
3. In the initial terminal, text with ANSI escape codes is still sent, and the terminal is inoperable and/or wrongly colored.

OS: Macos 10.14

![](https://dl.dropboxusercontent.com/s/bwje73qxonf1iyu/termshark_kill_issue.png)

**Comment by gcla** [comment]
Thanks for the report, I'll reproduce it here!

**Comment by wfailla** [comment]
I can reproduce this on:

```
-> % cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by iamasmith** [comment]
Just a note on this one as a root cause but that also it is generally impossible to fix for things like disconnects from a remote instance such as ssh or kubectl instead of a kill -KILL.

The cause of the continuous spray of ANSI sequences is because the UI library has put the terminal in a mouse event mode which causes it to stream codes back to the library to handle mouse positioning and clicks.

If this happens then a reset of the terminal on a Mac standard Terminal.app this is Cmd-K and on Gnome terminal there is an option in the top menu bar. If you must you can also use the 'reset' command on macOS or Linux from the terminal but you will have to Ctrl-C to go to a new line and not mouse over the terminal to avoid creating any new mouse events to be able to type it.

The teardown for the mouse event handler should be done on a SIGHUP handler (I didn't check the code) but this is limited by how your are accessing it - for example this won't benefit you if you lose a network connection to it.
