### ISSUE TITLE
termshark in termux not running 

### ISSUE THREAD

**Issue by saeedo201** [gcla/termshark#122]
![Screenshot_٢٠٢١٠٤١٩-٠٤٢٢٥٠_Termux](https://user-images.githubusercontent.com/44009760/115173486-b4f7b200-a0c7-11eb-8963-d70cce52b2e6.jpg)

![Uploading Screenshot_٢٠٢١٠٤١٩-٠٤٢٣١٦_Termux.jpg…]()

**Comment by saeedo201** [comment]
i actually installed termux api

**Comment by gcla** [comment]
Hi @saeedo201 - can you provide some more information? I think that in order to use termshark to capture packets on your device, you'll need to root it first then install some sort of su tool like https://supersuroot.org/. My phone is not rooted so I haven't tried this myself. Does termshark run correctly on your device if you give it a pcap? e.g.
```
termshark -r test.pcap
```

**Comment by gcla** [comment]
Hi @saeedo201 - I'm sorry I didn't get to the bottom of this. If it's still a problem for you, please do re-open.
