### ISSUE TITLE
Feature request: Follow TCP stream

### ISSUE THREAD

**Issue by RobertLarsen** [gcla/termshark#29]
Totally love this tool but would even more so if it had the "Follow Stream" feature from Wireshark...perhaps the feature I depend on the most.

**Comment by gcla** [comment]
Hi @RobertLarsen - would you be willing to try a test termshark binary that supports stream reassembly? Let me know!

**Comment by RobertLarsen** [comment]
Hi
I would love to test this.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gcla** [comment]
Much appreciated :-) I've pushed the stream reassembly code to a branch called streams. Travis just built the binaries - here's the link for linux:

https://storage.googleapis.com/termshark/19323fab64966ef6b03f3182eeb94615e1cb81eb/termshark_linux_amd64/termshark

and here's the link for macos:

https://storage.googleapis.com/termshark/19323fab64966ef6b03f3182eeb94615e1cb81eb/termshark_darwin_amd64/termshark

You can get to stream reassembly by selecting a TCP or UDP packet in the packet list, then hitting Esc -> Analysis -> Reassemble stream.

The binaries are very lightly tested :-/ My automated testing is very much lacking. There's a battery of manual tests I'll run through before I make it official, so please don't hesitate to shout if anything doesn't work, has regressed from v1, etc. Thanks!

**Comment by gcla** [comment]
One thing I know is not right, but I might tolerate in the short-term, is the handling of stream data such as you might see in an interactive session over the network. I looked at an old telnet example - if the user had typed "abc" (each character in its own packet), in ascii mode Wireshark shows "abc" contiguously, but because termshark uses a list widget behind the scenes, it will show "a", "b" and then "c" in separate list elements. I didn't notice that till late on. In both Wireshark and termshark, clicking the "b" will select the packet which contains the "b" payload, so I knew I needed some kind of widget with click support, but to make the UI the same as Wireshark, I needed click support in arbitrary regions of a 2d canvas. I don't yet have a gowid component yet that does that out of the box. It's not difficult, but I might leave as-is for v2. If you are looking at a protocol that is more line-based, like http, then both UIs are similar. Let me know what you think - is that presentation difference a show-stopper?

**Comment by RobertLarsen** [comment]
Hi
I've tried it out and it looks great. However I'm not a big fan of the scrolling. I am looking at a HTTP session and the request part fills almost the entire screen, but a little part of the response is showing near the bottom of the terminal. When I press the down key I scroll the entire request part away (20 something lines). Press down again and the screen scrolls one line. Wouldn't it be better to always scroll one line?

I have another feature request. It could be nice to be able to toggle the hex part of the stream. With text based protocols I prefer to see just text.

These are minor things...I love it already :-)
Keep it up!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by RobertLarsen** [comment]
> I have another feature request. It could be nice to be able to toggle the hex part of the stream. With text based protocols I prefer to see just text.

Nevermind. I see now that you already thought of that :-)

**Comment by gcla** [comment]
Thanks. I agree the scrolling is wonky... I'd been ignoring it :-) I'll see if I can get you an improved binary soon.

**Comment by gcla** [comment]
Hi @RobertLarsen - I pushed a few small changes and have a new binary, if you'd like to replace the one you have. It's not that different really:

- when in stream reassembly ascii mode, the list items are framed at the sides only, so there's more vertical space to show the stream content, and the chunks are closer together on the screen
- the scrolling is slightly better, though still not ideal. I considered the line-by-line scroll - what makes that a little tricky is support for it in the underlying list widget, which wants to know which stream "chunk" has focus. It's a good idea, it just needs work on the gowid-side of things. Right now, if the current chunk doesn't fit on the screen, it scrolls line-by-line until you reach the bottom, then when the next chunk gets focus, it scrolls that up far enough that you can see as much as can fit on the screen. So it sometimes flips from line, line, line to big jump. So that was by (questionable) design, I suppose, but there was also a bug - if you hit cursor down until you reached the next chunk, then hit cursor up, it would go right back to the top of the previous stream chunk (its first line), instead of going back to the bottom (its last line). I fixed that. So you can more easily switch from one stream chunk to the next and back - just up, down, up, down

Here's linux: 

https://storage.googleapis.com/termshark/61328129ae506dd0297001931d4f87e6cc627ee7/termshark_linux_amd64/termshark

and here's MacOS:

https://storage.googleapis.com/termshark/61328129ae506dd0297001931d4f87e6cc627ee7/termshark_darwin_amd64/termshark

**Comment by gcla** [comment]
Closing this now v2 is out.
