### ISSUE TITLE
Could not gread PDML data: XML syntax error on line 39343: unexpected EOF

### ISSUE THREAD

**Issue by denyspozniak** [gcla/termshark#3]
Hello!
Got error when trying to analyze SIP protocol:

![image](https://user-images.githubusercontent.com/22612345/56561203-456d8b80-65af-11e9-9f5f-4793737cbe77.png)

**Comment by gcla** [comment]
Drat, sorry! This might be too much to ask, but could you (privately) share the pcap, or maybe some of it? If not, any more specific info on the traffic would be useful to help me reproduce. In the meantime I'll look for a SIP pcap and see if that's enough to trigger it.

**Comment by denyspozniak** [comment]
Please share your email, I will send pcap file. But as I can see issue happens in realtime mode only.
I tried to open like `./termshark -r=pdml.pcap` but no luck

**Comment by SatGarcia** [comment]
I'm getting the same exact problem (different line number reported though).

**Comment by gcla** [comment]
hi @denyspozniak - thanks, my email address is grclark@gmail.com

**Comment by pocc** [comment]
Another good option is to post a dropbox/ google drive link to the pcap so it’s a part of the issue.

**Comment by pocc** [comment]
@denyspozniak do we have an update? If you do have the pcap, please post a link here.

**Comment by denyspozniak** [comment]
Hello! I have sent pcap file on e-mail.

**Comment by gcla** [comment]
Sorry it took me so long to acknowledge - I'm going to look at this next.

**Comment by sagis-tikal** [comment]
Hi all, I am facing this issue as well.

**Comment by pocc** [comment]
@sagis-tikal Please post a link to the offending pcap so we can take a look.

**Comment by gcla** [comment]
I have a tentative theory about this. It doesn't happen with the pcap file, only when reading from the live interface. You can possibly see it in action with something like this - in one shell, run

```bash
tshark -i eth0 -s 0 -w crash.pcap
```

and in another shell run

```bash
while [ 1 ] ; do tshark -r crash.pcap -T pdml > /dev/null ; done
```

Let it run for a minute. I see occasional 

```
tshark: The file "crash.pcap" appears to have been cut short in the middle of a packet.  
```

Termshark is complaining because while generating the structured packet view via `tshark -T pdml`, it is receiving malformed XML. My guess from xml.go:290 is that the error means the tshark command terminated without closing some XML tags - maybe because it reaches EOF half-way through a packet being written by `tshark -i eth0 ...`, also running via termshark.

The theory's tentative because, at least for me, every time I see this error I still receive valid XML/PDML from tshark - confirmed with xmllint. I assumed that would always be the case. But maybe older versions of tshark terminated less cleanly and didn't close some PDML tags. My tshark is v2.6.8. @sagis-tikal and @denyspozniak - what version of tshark are you using?

I'm looking through the wireshark source to see if I can see any changes that suggest this was once an issue.

**Comment by sagis-tikal** [comment]
> 
> 
> @sagis-tikal Please post a link to the offending pcap so we can take a look.

I'm sorry, but I'm not allowed to send PCAP files of the traffic.

@gcla I was using tshark v1.12.1, but I just upgraded to v2.6.6 and the issue seems to have disappeared.

Thanks guys :)

**Comment by gcla** [comment]
Thanks for the report, @sagis-tikal - I am more confident the older tshark is triggering this behavior. Here's an updated test. In one shell, run

```bash
while [ 1 ] ; do timeout 15s tshark -i eth0 -s 0 -w crash.pcap ; done
```

then in another run

```bash
script -c 'for i in $(seq 1 1000) ; do tshark -r crash.pcap -T pdml >> pdmldata-${i}.xml || echo FAILED $i ; echo did $i ; done'
```

To check the generated pdml, run

```bash
cat typescript | grep FAILED | nawk '{print $2}' | dos2unix | xargs -i xmllint --noout pdmldata-{}.xml || echo failed {}
```

If I do this with tshark 2.6.8, the XML is always well-formed. If I use 1.10.2, which I happen to have installed, then I see XML files without the closing `</pdml>` tag.

I guess it might not always be an option to upgrade tshark. I think I can make termshark more forgiving and not terminate the capture on this error. After all, it won't affect the correctness of the result. I'll shout when I have a patch ready.

**Comment by sagis-tikal** [comment]
Sounds great!
I don't really have another testing machine with 1.10.2 installed and I can't really downgrade the one I just upgraded. 
But I'd love to help test the patch in-case I'll be able to.

Thanks again for giving so much for the community :)

**Comment by gcla** [comment]
Hi @sagis-tikal , @denyspozniak , @elsaturnino - I've put a test binary up at this link:

https://storage.googleapis.com/termshark/f7b32a1addc23d32f5a2a9a148495a17aa42d9ed/termshark_linux_amd64/termshark

If upgrading tshark works for you, that's probably easier. If not, this binary shouldn't halt with the unexpected EOF error.
