### ISSUE TITLE
Feature Request: keep already expand options be expand while view cross different packet

### ISSUE THREAD

**Issue by Ivlyth** [gcla/termshark#32]

**Comment by gcla** [comment]
Hi - just a question or two to clarify this for me - say you're on packet #1, and you have expanded the Ethernet layer in the packet structure view. If you then move to packet #2, is your request to have the Ethernet layer (if present) expand itself too? If you were to then expand the IPv4 layer in packet #2 and move back to packet #1, should IPv4 (if present) expand itself in packet #1? I'll take a look at Wireshark's behavior as well so that I can understand this better.

**Comment by gcla** [comment]
sorry, should've tagged you @MythRen

**Comment by pocc** [comment]
They're a participant, so they will get notified when you respond, regardless of whether you tag.
You also should use some other syntax (like `#1` with backticks or # 1) to refer to ordinal numbers as otherwise you're linking to issues.

**Comment by Ivlyth** [comment]
@gcla yes, it's better to keep options pane to stay the same state cross packets (what options is expand keep expand, if present), just like wireshark does

wish i could help you.  :)

**Comment by gcla** [comment]
Hi @MythRen - would you mind giving branch `keepexpanded` a try? It's my first go at implementing this feature, copying Wireshark's behavior, more or less. This should get it built:

```bash
git clone https://github.com/gcla/termshark
cd termshark
git checkout keepexpanded
export GO111MODULE=on
go install ./...
```

Then run `~/go/bin/termshark`

Thanks :-)

**Comment by gcla** [comment]
I've merged back to master. Let me know of any bugs...

**Comment by Ivlyth** [comment]
@gcla sorry for late.   i test 2.0 recently, it works fine for me.

**Comment by gcla** [comment]
thanks @MythRen :)
