### ISSUE TITLE
Adhere to Semantic Versioning

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#53]
[SemVer](https://semver.org/) is a way to track versions. Termshark has added many features/fixes since initial release, but only has one version. For feature adds since v1, increment minor (1.[**2**].3) and for bugfixes, increment patch (1.2.[**3**]). I'm proposing to call latest commit, 74abf8ffb5fab2d150c8a185ff76071d0eaa2aec "v1.1.0" as a bundle of all previous features/fixes, but to increment version in future with features/patches in mind.

What do you think?

**Comment by gcla** [comment]
I do plan to stick to semantic versioning, but have been deliberately holding off making another official release yet because I don't feel the most recent changes are as thoroughly tested as v1.0.0 was. Unfortunately the automated tests are pretty poor at the moment, so I can't just run a script and be as confident that I haven't broken things. I have a prototype of something that runs termshark under socat and then greps the output for various things, but it's messy and unfinished. It's a project unto itself. Most of the features I'd like for v1.1.0 are there now - the big one that's missing is stream reassembly. Once I have that working, I'll spend some time testing then make the release. And then I should focus on automating the testing :-/ If the testing was more thorough, I'd feel better about making official minor version and patch releases.
