### ISSUE TITLE
Merge gcla/tail changes back to maintainer

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#74]
## bug report/feature request/ask

gcla/tail can't take issues and I have a couple of thoughts:
* It currently references hpcloud/tail, which isn't being maintained (according to [this issue](https://github.com/hpcloud/tail/issues/150) since 2016)
* I want to use it for a project 👍; current references to hpcloud/tail in gcla/tail break when I use it (like #72).
* [nxadm/tail](https://github.com/nxadm/tail) is a successor project and could benefit from your bytes contributions

**Comment by gcla** [comment]
Hi - interesting, and thanks for the nxadm/tail lead. Maybe I should open an issue and ask if they'd be interested in tailing by bytes rather than by line. The code I hacked in and renamed gcla/tail was pretty cheesy and I'd feel sheepish offering it up as-is though.

**Comment by dawidd6** [comment]
I'm currently trying to upgrade `termshark` in Debian and I would need to package your fork of `tail` fork. It would be better to package just the fork, I guess, so I'm gonna wait a bit if you decide to contribute your changes to upstream.

**Comment by pocc** [comment]
I can take care of the merge and cleanup of code at some point. This will likely mean instead of using replacements of bytes for strings, parallel methods are used.

**Comment by gcla** [comment]
Hi @dawidd6 - quick question for you. The tail fork package is only needed on termshark for Windows because on Linux and friends we can just rely on the familiar tail command being installed. If the uses of gcla/tail were only within Go files that were compiled only on Windows (e.g. `+build windows`), would that remove the need for packaging gcla/tail for termshark on Debian? I'm not familiar with the Debian packaging procedures. Also - thank you for packaging it up, I wouldn't know where to start - much appreciated...

**Comment by dawidd6** [comment]
@gcla yea, using build tags should eliminate the need to package this dependency, since it would be windows only. Good solution!

**Comment by gcla** [comment]
@pocc - I opened this issue against `nxadm/tail`, to see if they're interested in byte-level tailing: https://github.com/nxadm/tail/issues/13

**Comment by pocc** [comment]
Cheers

**Comment by pocc** [comment]
Cheers!

**Comment by nxadm** [comment]
Just a small note that I haven't forgotten the issue, but that I am busy merging and reviewing the many issues and PRs open on the dormant upstream project. Because nxadm/tail is starting to get some traction (as fas as I can see from git clones and the addition to Fedora/Debian/Ubuntu), I am extra careful not to break stuff :).

**Comment by gcla** [comment]
Just cleaning up - please re-open if this would still be useful to have.
