### ISSUE TITLE
Reload file automatically while reading file.

### ISSUE THREAD

**Issue by kevinhwang91** [gcla/termshark#97]
### Is your feature request related to a problem? Please describe.
It seems that I can't reload a file, but not a fifo while reading file. 

The file produce by `sudo tcpdump -U -w file`, read file by `termshark -r file`. When the data append to the file, data in termshark can't be updated.

### Describe the solution you'd like
Read normal file like fifo.

### Describe alternatives you've considered
termshark could switch `display filter` to `capture filter` mode is the best solution I guess.

**Comment by gcla** [comment]
Hi @kevinhwang91 - interesting idea, I'll think about this. If you think of termshark as just a tui interface around tshark, then maybe you wouldn't expect it to be able to do this, since you wouldn't expect tshark to function like `tail -f`. But, perhaps it's more reasonable to have the viewpoint that this idea is useful, so let's make termshark do it ;-) 

Do you feel strongly about it being a native feature, or would a workaround do the job for you? e.g.

```
touch foo.pcap
tail -f -c1 foo.pcap | termshark -r -
```

then elsewhere, append data to `foo.pcap`. Here's an example of slowly feeding data in:

```
pv -q -L 100 bar.pcap >> foo.pcap
```

**Comment by kevinhwang91** [comment]
Before opening this issue, I have tried to run `sudo tcpdump -U -w foo.pcap` in one terminal, and run `tail -f foo.pcap | termshark` in another. But termshark exits and complains:

`Error running command [command: /home/kevin/.local/bin/termshark [termshark -i /dev/fd/3 -w /home/kevin/.cache/termshark/pcaps/_dev_fd_3--2020-09-19--16-13-29.pcap], error: exit status 1]`

A workaround following your steps will work, but it seems that the precondition is `touch` an empty file, I think this workaround is cumbersome.

I'd to termshark could add a button or menu selection for reloading the file.

Btw, I'm not sure the below feature is related to this issue.
I switch `capture` to `display` in order to stop the data output, if I want to enter `capture` again, I must restart termshark. 

If this is the case, I think termshark is more suitable for analysis rather than data collection, because the user experience is not good enough for a collection.

**Comment by gcla** [comment]
Hi @kevinhwang91 - could you try this sequence instead:
```
shell1$ sudo tcpdump -U -w foo.pcap
shell2$ tail -f -c +0 foo.pcap | termshark 
```

**Comment by kevinhwang91** [comment]
> Hi @kevinhwang91 - could you try this sequence instead:
> 
> ```
> shell1$ sudo tcpdump -U -w foo.pcap
> shell2$ tail -f -c +0 foo.pcap | termshark 
> ```

It works for me!
